image:
    file: .gitpod.Dockerfile
ports:
    - port: 5901
      onOpen: ignore
    - port: 6081
      onOpen: open-preview
tasks:
    - name: install cypress to workspace
      init: |
          npm install
    - name: run chrome tests
    - command: |
        sudo install -d -m 0755 /etc/apt/keyrings
        wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
        echo '
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
          ' | sudo tee /etc/apt/preferences.d/mozilla
        sudo apt-get update -y && sudo apt-get install firefox -y --allow-downgrades



